spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html

  # Auto Update
  # JPA 미 사용 시 주석처리
  jpa:
    hibernate:
      ddl-auto: update

# mybatis 미 사용 시 주석처리
#mybatis:
#  mapper-locations:mapper/*.xml

server:
  port: 65535