spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  config-location: classpath:mybatis-config.xml



server:
  port: 65535