spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  # ?? ??? ??? Update
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 65535